fix github actions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,44 +26,44 @@ jobs:
           name: astro-build
           path: dist/
 
-  deploy-on-test:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Download build artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: astro-build
-          path: dist/
-
-      - name: Deploy to prod OVH Server
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          SERVER_USER: ${{ secrets.SERVER_USER }}
-          SERVER_IP: ${{ secrets.SERVER_IP }}
-          SERVER_PATH: "/var/www/test.pcoundia.com/"
-        run: |
-          # Vérification des variables
-          if [[ -z "$SSH_PRIVATE_KEY" || -z "$SERVER_USER" || -z "$SERVER_IP" ]]; then
-            echo "Error: Missing environment variables!"
-            exit 1
-          fi
-
-          # Configure SSH for access
-          mkdir -p ~/.ssh
-          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | tee ~/.ssh/id_rsa > /dev/null
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
-
-          # Test SSH connection
-          ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "echo 'SSH connection successful'"
-
-          # Clear target directory on the server (optional but recommended)
-          ssh "$SERVER_USER@$SERVER_IP" "rm -rf $SERVER_PATH/*"
-
-          # Deploy to the production server
-          rsync -avzL --chown=$SERVER_USER:www-data --chmod=775 --delete dist/ "$SERVER_USER@$SERVER_IP:$SERVER_PATH" -v
-  
+#  deploy-on-test:
+#    needs: build
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Download build artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          name: astro-build
+#          path: dist/
+#
+#      - name: Deploy to prod OVH Server
+#        env:
+#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+#          SERVER_USER: ${{ secrets.SERVER_USER }}
+#          SERVER_IP: ${{ secrets.SERVER_IP }}
+#          SERVER_PATH: "/var/www/test.pcoundia.com/"
+#        run: |
+#          # Vérification des variables
+#          if [[ -z "$SSH_PRIVATE_KEY" || -z "$SERVER_USER" || -z "$SERVER_IP" ]]; then
+#            echo "Error: Missing environment variables!"
+#            exit 1
+#          fi
+#
+#          # Configure SSH for access
+#          mkdir -p ~/.ssh
+#          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | tee ~/.ssh/id_rsa > /dev/null
+#          chmod 600 ~/.ssh/id_rsa
+#          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
+#
+#          # Test SSH connection
+#          ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "echo 'SSH connection successful'"
+#
+#          # Clear target directory on the server (optional but recommended)
+#          ssh "$SERVER_USER@$SERVER_IP" "rm -rf $SERVER_PATH/*"
+#
+#          # Deploy to the production server
+#          rsync -avzL --chown=$SERVER_USER:www-data --chmod=775 --delete dist/ "$SERVER_USER@$SERVER_IP:$SERVER_PATH" -v
+#
 
 #  selenium-test:
 #    runs-on: ubuntu-latest
@@ -96,6 +96,7 @@ jobs:
 
   deploy-on-prod:
 #    needs: selenium-test
+    needs: build
     runs-on: ubuntu-latest
     steps:
       - name: Download build artifacts
