feat: add deploy on test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,7 +26,7 @@ jobs:
           name: astro-build
           path: dist/
 
-  deploy:
+  deploy-on-test:
     needs: build
     runs-on: ubuntu-latest
     steps:
@@ -36,7 +36,55 @@ jobs:
           name: astro-build
           path: dist/
 
-      - name: Deploy to OVH Server
+      - name: Deploy to test OVH Server
+        env:
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          SERVER_USER: ${{ secrets.SERVER_USER }}
+          SERVER_IP: ${{ secrets.SERVER_IP }}
+          SERVER_PATH: "/var/www/test.pcoundia.com/"
+        run: |
+          # Vérification des variables
+          if [[ -z "$SSH_PRIVATE_KEY" || -z "$SERVER_USER" || -z "$SERVER_IP" ]]; then
+            echo "Error: Missing environment variables!"
+            exit 1
+          fi
+          
+          # Configuration of SSH
+          mkdir -p ~/.ssh
+          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | tee ~/.ssh/id_rsa > /dev/null
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
+          
+          # Test SSH
+          ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "echo 'SSH connection successful'"
+ 
+          rsync -avz --chown=$SERVER_USER:www-data --chmod=775 --delete dist/ "$SERVER_USER@$SERVER_IP:$SERVER_PATH"
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout Selenium Tests Repository
+        run: |
+          git clone https://github.com/coundia/selenium-java-pcoundia.git selenium-tests
+
+      - name: Run Selenium Tests
+        env:
+          SERVER_URL: "https://pcoundia.com"
+        run: |
+          cd selenium-tests
+          mvn clean test -Dapp.url=$SERVER_URL
+
+  deploy-on-prod:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download build artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: astro-build
+          path: dist/
+
+      - name: Deploy to prod OVH Server
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           SERVER_USER: ${{ secrets.SERVER_USER }}
@@ -57,6 +105,5 @@ jobs:
           
           # Test SSH
           ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" "echo 'SSH connection successful'"
- 
+          
           rsync -avz --chown=$SERVER_USER:www-data --chmod=775 --delete dist/ "$SERVER_USER@$SERVER_IP:$SERVER_PATH"
- 
